name: Update Creative News Global
on:
  schedule:
    - cron: '0 */2 * * *'   # 每 2 小时
  workflow_dispatch:        # 手动按钮
jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      PROXY_URL: ${{ secrets.PROXY_URL }}   # 外网源代理（可选）
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install axios rss-parser https-proxy-agent
      - run: node scripts/crawl.js
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/posts.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: creative news $(date -u +%F_%H:%M)" && git push)
